---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-templated-admin-client-credentials
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-admin-client-credentials
  request:
    templatedConfig:
      type: helm
      templates:
        admin_client_credentials.yml: |
          oauth:
            clients:
              admin:
                secret: '{{.Values.client_credentials}}'
      values:
        client_credentials:
          name: uaa-admin-client-credentials
          key: "password"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-admin-client-credentials
  namespace: concourse
spec:
  type: password
  secretName: uaa-admin-client-credentials
