#! TODO: refactor this? split credhub and concourse user credentials to separate files? 
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-templated-admin-client-credentials
  namespace: concourse
spec:
  type: templatedconfig
  secretName: credhub-admin-client-credentials
  request:
    templatedConfig:
      type: helm
      templates:
        credhub_admin_client_credentials.yml: |
          oauth:
            clients:
              credhub_admin_client:
                secret: '{{.Values.client_credentials}}'
      values:
        client_credentials:
          name: credhub-admin-client-credentials
          key: "password"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-templated-concourse-user-credentials
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-concourse-user-credentials
  request:
    templatedConfig:
      type: helm
      templates:
        concourse_user_credentials.yml: |
          scim:
            users:
            - admin|{{.Values.client_credentials}}|admin@admin.tld|first|last|clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write,openid|uaa
            - credhub_admin_client|{{.Values.credhub_admin_client_credentials}}|credhub@credhub.tld|first|last|credhub.read,credhub.write|uaa
            - credhub_client|{{.Values.credhub_client_user_credentials}}|credhub@credhub.tld|first|last|credhub.read,credhub.write|uaa2
      values:
        client_credentials:
          name: "concourse-admin-user-credentials"
          key: "password"
        credhub_admin_client_credentials:
          name: "credhub-admin-client-credentials"
          key: "password"
        credhub_client_user_credentials:
          name: "credhub-client-user-credentials"
          key: "password"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: concourse-admin-user-credentials
  namespace: concourse
spec:
  type: password
  secretName: concourse-admin-user-credentials

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-client-user-credentials
  namespace: concourse
spec:
  type: password
  secretName: credhub-client-user-credentials

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-admin-client-credentials
  namespace: concourse
spec:
  type: password
  secretName: credhub-admin-client-credentials
