---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-templated-concourse-user-credentials
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-concourse-user-credentials
  request:
    templatedConfig:
      type: helm
      templates:
        concourse_user_credentials.yml: |
          scim:
            users:
            - admin|{{.Values.client_credentials}}|admin@admin.tld|first|last|clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write,openid|uaa
      values:
        client_credentials:
          name: "concourse-admin-user-credentials"
          key: "password"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: concourse-admin-user-credentials
  namespace: concourse
spec:
  type: password
  secretName: concourse-admin-user-credentials
