---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-templated-admin-client-credentials
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-credhub-admin-client-credentials
  request:
    templatedConfig:
      type: helm
      templates:
        credhub_admin_client_credentials.yml: |
          oauth:
            clients:
              credhub_admin_client:
                secret: '{{.Values.credhub_admin_client_credentials}}'
          scim:
            users:
            - credhub_admin_client|{{.Values.credhub_admin_client_credentials}}|credhub@credhub.tld|first|last|credhub.read,credhub.write|uaa
            - credhub_client|{{.Values.credhub_client_user_credentials}}|credhub@credhub.tld|first|last|credhub.read,credhub.write|uaa2
      values:
        credhub_admin_client_credentials:
          name: "credhub-admin-client-credentials"
          key: "password"
        credhub_client_user_credentials:
          name: "credhub-client-user-credentials"
          key: "password"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-admin-client-credentials
  namespace: concourse
spec:
  type: password
  secretName: credhub-admin-client-credentials

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-client-user-credentials
  namespace: concourse
spec:
  type: password
  secretName: credhub-client-user-credentials
