---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-templated-database-credentials
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-database-credentials
  request:
    templatedConfig:
      type: helm
      templates:
        database_credentials.yml: |
          database:
            username: uaa
            password: '{{.Values.postgresqlPassword}}'
      values:
        postgresqlPassword:
          name: "uaa-postgresql-password"
          key: "password"

#! "uaa-postgresql-password" secret is defined in config/database module
