---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-encryption-keys
  namespace: concourse
spec:
  type: templatedconfig
  secretName: encryption-keys
  request:
    templatedConfig:
      type: helm
      templates:
        encryption_keys.yml: |
          encryption:
            active_key_label: default_encryption_key
            encryption_keys:
            - label: default_encryption_key
              passphrase: '{{.Values.client_credentials}}'
      values:
        client_credentials:
          name: "encryption-key"
          key: "password"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: encryption-key
  namespace: concourse
spec:
  type: password
  secretName: encryption-key
