---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-jwt-policy-signing-keys
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-jwt-policy-signing-keys
  request:
    templatedConfig:
      type: helm
      templates:
        jwt_policy_signing_keys.yml: |
          jwt:
            token:
              policy:
                activeKeyId: default_jwt_policy_key
                keys:
                  default_jwt_policy_key:
                    signingKey: '{{.Values.private_key}}'
      values:
        private_key:
          name: "jwt-keys"
          key: "private_key"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: jwt-keys
  namespace: concourse
spec:
  type: rsa
  secretName: jwt-keys
