---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-saml-keys-file
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-saml-keys
  request:
    templatedConfig:
      type: helm
      templates:
        saml_keys.yml: |
          login:
            saml:
              activeKeyId: default_saml_key
              keys:
                default_saml_key:
                  key: |
                    {{ .Values.private_key | indent 10 | trim }}
                  certificate: |
                    {{ .Values.certificate | indent 10 | trim }}
                  passphrase: ""
      values:
        certificate:
          name: "uaa.saml-keys"
          key: "certificate"
        private_key:
          name: "uaa.saml-keys"
          key: "private_key"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  namespace: concourse
  name: uaa.saml-keys-ca
spec:
  request:
    certificate:
      alternativeNames: null
      commonName: CA
      isCA: true
      signerType: local
  secretName: uaa.saml-keys-ca
  type: certificate

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  namespace: concourse
  name: uaa.saml-keys
spec:
  request:
    certificate:
      CAKeyRef:
        key: private_key
        name: uaa.saml-keys-ca
      CARef:
        key: certificate
        name: uaa.saml-keys-ca
      alternativeNames: null
      commonName: uaa_login_service_provider
      isCA: false
      signerType: local
  secretName: uaa.saml-keys
  type: certificate
