#@ load("@ytt:template", "template")
#@ load("@ytt:yaml", "yaml")

#@ def quarks_secret_uaa_client_credential_template(client_name):
oauth:
  #@yaml/text-templated-strings
  clients:
    (@= client_name @):
      secret: "{{.Values.client_credentials}}"
#@ end

#@ def quarks_secret_uaa_client_credentials(client_name, credential_reference):
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: #@ "uaa-templated-" + credential_reference
spec:
  type: templatedconfig
  secretName: #@ "uaa-" + credential_reference
  request:
    templatedConfig:
      type: helm
      templates:
        client_credentials.yml: #@ yaml.encode(quarks_secret_uaa_client_credential_template(client_name))
      values:
        client_credentials:
          name: #@ credential_reference
          key: "password"
#@ end

#@ def quarks_secret_uaa_concourse_admin_user_credential_template():
scim:
  users:
  - "admin|{{.Values.client_credentials}}|admin@admin.tld|first|last|clients.read,cloud_controller.admin,doppler.firehose,network.admin,openid,routing.router_groups.read,routing.router_groups.write,scim.read,scim.write|uaa"
#@ end

#@ def quarks_secret_uaa_concourse_admin_user_credentials():
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: "uaa-templated-concourse-admin-user-credentials"
spec:
  type: templatedconfig
  secretName: "uaa-concourse-admin-user-credentials"
  request:
    templatedConfig:
      type: helm
      templates:
        concourse_admin_user_credentials.yml: #@ yaml.encode(quarks_secret_uaa_concourse_admin_user_credential_template())
      values:
        client_credentials:
          name: "concourse-admin-user-credentials"
          key: "password"
#@ end

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: concourse-admin-user-credentials
spec:
  type: password
  secretName: concourse-admin-user-credentials

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-admin-client-credentials
spec:
  type: password
  secretName: uaa-admin-client-credentials

--- #@ template.replace(quarks_secret_uaa_client_credentials("admin", "uaa-admin-client-credentials"))
--- #@ template.replace(quarks_secret_uaa_concourse_admin_user_credentials())