---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: host-key
  namespace: concourse
spec:
  type: ssh
  secretName: host-key

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: worker-key
  namespace: concourse
spec:
  type: ssh
  secretName: worker-key

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: session-signing-key
  namespace: concourse
spec:
  type: rsa
  secretName: session-signing-key

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: local-user
  namespace: concourse
spec:
  type: basic-auth
  secretName: local-user

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: templated-concourse-web
  namespace: concourse
spec:
  type: templatedconfig
  secretName: concourse-web
  request:
    templatedConfig:
      type: helm
      templates:
        host-key: "{{.Values.hostKey}}"
        session-signing-key: "{{.Values.sessionSigningKey}}"
        worker-key-pub: "{{.Values.workerKeyPub}}"
        local-users: "{{.Values.localUserName}}:{{.Values.localUserPassword}}"
        postgresql-user: "concourse"
        postgresql-password: "{{.Values.postgresqlPassword}}"
        credhub-client-id: credhub_admin_client
        credhub-client-secret: "{{.Values.credhubClientSecret}}"
        credhub-ca-cert: "{{.Values.credhubCaCert}}"
        github-client-id: "{{.Values.githubID}}"
        github-client-secret: "{{.Values.githubSecret}}"
      values:
        hostKey:
          name: "host-key"
          key: "private_key"
        sessionSigningKey:
          name: "session-signing-key"
          key: "private_key"
        workerKeyPub:
          name: "worker-key"
          key: "public_key"
        localUserName:
          name: "local-user"
          key: "username"
        localUserPassword:
          name: "local-user"
          key: "password"
        postgresqlPassword:
          name: "concourse-postgresql-password"
          key: "password"
        credhubClientSecret:
          name: "credhub-admin-client-credentials"
          key: "password"
        credhubCaCert:
          name: "credhub.ca"
          key: "certificate"
        githubID:
          name: github
          key: id
        githubSecret:
          name: github
          key: secret

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: templated-concourse-worker
  namespace: concourse
spec:
  type: templatedconfig
  secretName: concourse-worker
  request:
    templatedConfig:
      type: helm
      templates:
        host-key-pub: "{{.Values.hostKeyPub}}"
        worker-key: "{{.Values.workerKey}}"
      values:
        hostKeyPub:
          name: "host-key"
          key: "public_key"
        workerKey:
          name: "worker-key"
          key: "private_key"
