#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")

#@ def add_database_user(name):
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: #@ name
  namespace: concourse
  annotations:
    cnrm.cloud.google.com/project-id: #@ data.values.google.project_id
spec:
  instanceRef:
    external: #@ data.values.database.name
  password:
    valueFrom:
      secretKeyRef:
        name: #@ name + "-postgresql-password"
        key: password
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: #@ name + "-postgresql-password"
  namespace: concourse
spec:
  type: password
  secretName: #@ name + "-postgresql-password"
#@ end

--- #@ template.replace(add_database_user("concourse"))
--- #@ template.replace(add_database_user("credhub"))
--- #@ template.replace(add_database_user("uaa"))
