#@ load("@ytt:template", "template")
#@ load("@ytt:yaml", "yaml")

#@ def quarks_secret_uaa_client_credential_template(client_name):
oauth:
  #@yaml/text-templated-strings
  clients:
    (@= client_name @):
      secret: "{{.Values.client_credentials}}"
#@ end

#@ def quarks_secret_uaa_client_credentials(client_name, credential_reference):
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: #@ "uaa-templated-" + credential_reference
  namespace: concourse
spec:
  type: templatedconfig
  secretName: #@ "uaa-" + credential_reference
  request:
    templatedConfig:
      type: helm
      templates:
        admin_client_credentials.yml: #@ yaml.encode(quarks_secret_uaa_client_credential_template(client_name))
      values:
        client_credentials:
          name: #@ "uaa-" + credential_reference
          key: "password"
#@ end

#@ def quarks_secret_credhub_client_credentials(client_name, credential_reference):
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: #@ "credhub-templated-" + credential_reference
  namespace: concourse
spec:
  type: templatedconfig
  secretName: #@ "credhub-" + credential_reference
  request:
    templatedConfig:
      type: helm
      templates:
        credhub_admin_client_credentials.yml: #@ yaml.encode(quarks_secret_uaa_client_credential_template(client_name))
      values:
        client_credentials:
          name: #@ "credhub-" + credential_reference
          key: "password"
#@ end

#@ def quarks_secret_uaa_concourse_user_credential_template():
scim:
  users:
  - "admin|{{.Values.client_credentials}}|admin@admin.tld|first|last|clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write,openid|uaa"
  - "credhub_admin_client|{{.Values.credhub_admin_client_credentials}}|credhub@credhub.tld|first|last|credhub.read,credhub.write|uaa"
  - "credhub_client|{{.Values.credhub_client_user_credentials}}|credhub@credhub.tld|first|last|credhub.read,credhub.write|uaa2"
#@ end

#@ def quarks_secret_uaa_concourse_user_credentials():
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-templated-concourse-user-credentials
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-concourse-user-credentials
  request:
    templatedConfig:
      type: helm
      templates:
        concourse_user_credentials.yml: #@ yaml.encode(quarks_secret_uaa_concourse_user_credential_template())
      values:
        client_credentials:
          name: "concourse-admin-user-credentials"
          key: "password"
        credhub_admin_client_credentials:
          name: "credhub-admin-client-credentials"
          key: "password"
        credhub_client_user_credentials:
          name: "credhub-client-user-credentials"
          key: "password"
#@ end

#@ def encryption_keys():
encryption:
  active_key_label: "default_encryption_key"
  encryption_keys:
  - label: default_encryption_key
    passphrase: "{{.Values.client_credentials}}"
#@ end

#@ def quarks_secret_uaa_encryption_keys():
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-encryption-keys
  namespace: concourse
spec:
  type: templatedconfig
  secretName: encryption-keys
  request:
    templatedConfig:
      type: helm
      templates:
        encryption_keys.yml: #@ yaml.encode(encryption_keys())
      values:
        client_credentials:
          name: "encryption-key"
          key: "password"
#@ end

#@ def saml_keys():
login:
  saml:
    activeKeyId: default_saml_key
    keys:
      default_saml_key:
        key: |
          {{ .Values.private_key | indent 10 | trim }}
        certificate: |
          {{ .Values.certificate | indent 10 | trim }}
        passphrase: ""
#@ end

#@ def quarks_secret_uaa_saml_keys():
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-saml-keys-file
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-saml-keys
  request:
    templatedConfig:
      type: helm
      templates:
        saml_keys.yml: #@ yaml.encode(saml_keys())
      values:
        certificate:
          name: "uaa.saml-keys"
          key: "certificate"
        private_key:
          name: "uaa.saml-keys"
          key: "private_key"
#@ end

#@ def jwt_keys():
jwt:
  token:
    policy:
      activeKeyId: "default_jwt_policy_key"
      keys:
        default_jwt_policy_key:
          signingKey: "{{.Values.private_key}}"
#@ end

#@ def quarks_secret_uaa_jwt_keys():
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-jwt-policy-signing-keys
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-jwt-policy-signing-keys
  request:
    templatedConfig:
      type: helm
      templates:
        jwt_policy_signing_keys.yml: #@ yaml.encode(jwt_keys())
      values:
        private_key:
          name: "jwt-keys"
          key: "private_key"
#@ end

#@ def database_credentials(password):
database:
  username: uaa
  password: #@ password
#@ end

#@ def quarks_uaa_database_credentials():
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-templated-database-credentials
  namespace: concourse
spec:
  type: templatedconfig
  secretName: uaa-database-credentials
  request:
    templatedConfig:
      type: helm
      templates:
        database_credentials.yml: #@ yaml.encode(database_credentials("{{.Values.postgresqlPassword}}"))
      values:
        postgresqlPassword:
          name: "uaa-postgresql-password"
          key: "password"
#@ end

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: concourse-admin-user-credentials
  namespace: concourse
spec:
  type: password
  secretName: concourse-admin-user-credentials

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-admin-client-credentials
  namespace: concourse
spec:
  type: password
  secretName: credhub-admin-client-credentials

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-client-user-credentials
  namespace: concourse
spec:
  type: password
  secretName: credhub-client-user-credentials


---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  namespace: concourse
  name: uaa.saml-keys-ca
spec:
  request:
    certificate:
      alternativeNames: null
      commonName: CA
      isCA: true
      signerType: local
  secretName: uaa.saml-keys-ca
  type: certificate

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  namespace: concourse
  name: uaa.saml-keys
spec:
  request:
    certificate:
      CAKeyRef:
        key: private_key
        name: uaa.saml-keys-ca
      CARef:
        key: certificate
        name: uaa.saml-keys-ca
      alternativeNames: null
      commonName: uaa_login_service_provider
      isCA: false
      signerType: local
  secretName: uaa.saml-keys
  type: certificate

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: jwt-keys
  namespace: concourse
spec:
  type: rsa
  secretName: jwt-keys

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: encryption-key
  namespace: concourse
spec:
  type: password
  secretName: encryption-key

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-admin-client-credentials
  namespace: concourse
spec:
  type: password
  secretName: uaa-admin-client-credentials

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: credhub-admin-client-credentials
  namespace: concourse
spec:
  type: password
  secretName: credhub-admin-client-credentials

--- #@ template.replace(quarks_secret_uaa_client_credentials("admin", "admin-client-credentials"))
--- #@ template.replace(quarks_secret_credhub_client_credentials("credhub_admin_client", "admin-client-credentials"))

--- #@ template.replace(quarks_secret_uaa_concourse_user_credentials())
--- #@ template.replace(quarks_secret_uaa_encryption_keys())
--- #@ template.replace(quarks_secret_uaa_saml_keys())
--- #@ template.replace(quarks_secret_uaa_jwt_keys())
--- #@ template.replace(quarks_uaa_database_credentials())

