#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ def add_concourse_namespace():
#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: concourse
#@ end

---
apiVersion: v1
kind: Namespace
metadata:
  name: concourse
  labels:
    quarks.cloudfoundry.org/monitored: concourse

--- #@ template.replace(overlay.apply(library.get("concourse").eval(), add_concourse_namespace()))
